// <auto-generated />
using MarsStreetView.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace MarsStreetView.Migrations
{
    [DbContext(typeof(MarsStreetViewDbContext))]
    [Migration("20180412174100_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MarsStreetView.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CameraName");

                    b.Property<string>("EarthDate");

                    b.Property<string>("Href");

                    b.Property<int?>("ListId")
                        .IsRequired();

                    b.Property<string>("RoverName");

                    b.Property<int>("Sol");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.ToTable("Favorite");
                });

            modelBuilder.Entity("MarsStreetView.Models.FavoriteList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("FavoriteList");
                });

            modelBuilder.Entity("MarsStreetView.Models.Favorite", b =>
                {
                    b.HasOne("MarsStreetView.Models.FavoriteList", "List")
                        .WithMany("Favorites")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
